### PR TITLE
Fix Travis CI setup and build regressions with Ogre 1.9

### PR DESCRIPTION
**Pull request by akien-mga**
See #1296.

### CODE REVIEW

File: source/camera/CameraManager.cpp [hunk 1]
```diff
@@ -86,22 +88,27 @@ CameraManager::CameraManager(Ogre::SceneManager* sceneManager, GameMap* gm, Ogre
...
-    //Create the Background Material
-    Ogre::MaterialPtr mat = Ogre::MaterialManager::getSingleton().getByName("Background");
 
     // Create background rectangle covering the whole screen
     Ogre::Rectangle2D* rect = new Ogre::Rectangle2D(BACKGROUND_RECT_NAME, true);
     rect->setCorners(-1.0, 1.0, 1.0, -1.0);
+#if defined(OGRE_VERSION) && OGRE_VERSION < 0x10A00
+    // setMaterial(const String&) is replaced by setMaterial(MaterialPtr&) in Ogre 1.10,
+    // and eventually dropped in Ogre 1.11.
+    rect->setMaterial("Background");
```
Comment (akien-mga) [inline source/camera/CameraManager.cpp:98]: Solves build error:
```
/home/travis/build/OpenDungeons/OpenDungeons/source/camera/CameraManager.cpp:95:26: error: no matching function for call to ‘Ogre::Rectangle2D::setMaterial(Ogre::MaterialPtr&)’
     rect->setMaterial(mat);
                          ^
```

File: source/render/MovableTextOverlay.cpp [hunk 2]
```diff
@@ -39,7 +40,11 @@ ChildOverlay::ChildOverlay(const Ogre::String& fontName, Ogre::Real charHeight,
     mTimeToDisplay(0),
     mFont(Ogre::FontManager::getSingleton().getByName(fontName))
 {
-    if(!mFont)
+#if defined(OGRE_VERSION) && OGRE_VERSION < 0x10A00
+    if (mFont.isNull())
```
Comment (akien-mga) [inline source/render/MovableTextOverlay.cpp:44]: Solves build error:
```
/home/travis/build/OpenDungeons/OpenDungeons/source/render/MovableTextOverlay.cpp:42:8: error: no match for ‘operator!’ (operand type is ‘Ogre::FontPtr {aka Ogre::SharedPtr<Ogre::Font>}’)
     if(!mFont)
        ^
```
Not sure if there would be a way to support both versions with the same syntax.

File: source/render/RenderManager.cpp [hunk 3]
```diff
@@ -1252,6 +1253,15 @@ std::string RenderManager::consoleListAnimationsForMesh(const std::string& meshN
...
     }
 
+#if defined(OGRE_VERSION) && OGRE_VERSION < 0x10A00
+    // For Ogre < 1.10 we still need to use Skeleton::BoneIterator
+    Ogre::Skeleton::BoneIterator boneIterator = objectEntity->getSkeleton()->getBoneIterator();
+    while (boneIterator.hasMoreElements())
+    {
+        std::string boneName = boneIterator.getNext()->getName();
+        ret += "\nBone: " + boneName;
+    }
```
Comment (akien-mga) [inline source/render/RenderManager.cpp:1263]: Solves build error:
```
/home/travis/build/OpenDungeons/OpenDungeons/source/render/RenderManager.cpp:1255:47: error: ‘class Ogre::SkeletonInstance’ has no member named ‘getBones’
     auto bones = objectEntity->getSkeleton()->getBones();
                                               ^
```

File: source/render/RenderManager.cpp [hunk 4]
```diff
@@ -1311,7 +1322,11 @@ std::string RenderManager::colourizeMaterial(const std::string& materialName, co
     //cout << "\nCloning material:  " << tempSS.str();
 
     // If this texture has been copied and colourized, we can return
+#if defined(OGRE_VERSION) && OGRE_VERSION < 0x10A00
+    if (!requestedMaterial.isNull())
```
Comment (akien-mga) [inline source/render/RenderManager.cpp:1326]: Solves build error:
```
/home/travis/build/OpenDungeons/OpenDungeons/source/render/RenderManager.cpp:1314:26: error: could not convert ‘requestedMaterial’ from ‘Ogre::MaterialPtr {aka Ogre::SharedPtr<Ogre::Material>}’ to ‘bool’
     if (requestedMaterial)
                          ^
```

**Comment by akien-mga** [comment]
Quite a few build regressions from #1293 to fix, we should have fixed Travis before merging it I guess ;)

File: source/utils/ResourceManager.cpp [hunk 5]
```diff
@@ -458,6 +459,23 @@ void ResourceManager::setupOgreResources(uint16_t shaderLanguageVersion)
...
+    Ogre::String archName = "";
+    while(seci.hasMoreElements())
+    {
+        secName = seci.peekNextKey();
+        Ogre::ConfigFile::SettingsMultiMap* settings = seci.getNext();
+        Ogre::ConfigFile::SettingsMultiMap::iterator i;
+        for (i = settings->begin(); i != settings->end(); ++i)
+        {
+            typeName = i->first;
+            archName = mGameDataPath + i->second;
```
Comment (akien-mga) [inline source/utils/ResourceManager.cpp:477]: Solves build issue:
```
/home/travis/build/OpenDungeons/OpenDungeons/source/utils/ResourceManager.cpp:461:30: error: ‘class Ogre::ConfigFile’ has no member named ‘getSettingsBySection’
     const auto settings = cf.getSettingsBySection();
                              ^
```

**Comment by akien-mga** [comment]
Finally it builds :) https://travis-ci.org/OpenDungeons/OpenDungeons/builds/445089620

I'll merge myself as it's quite important that we have working CI to prevent such issues in future PRs. We can still discuss and if needed rework the changes I outlined above.

File: source/render/MovableTextOverlay.cpp (hunk 2 above)
Comment (Bertram25) [reply source/render/MovableTextOverlay.cpp:44]: @akien-mga  std::shared_ptr-like objects usually have a `.get()` method to obtain the raw pointer:
https://www.ogre3d.org/docs/api/1.9/class_ogre_1_1_shared_ptr.html#a2c3ed4a7b5574c4e53adec450fd537b0

This could be used this way:
```c++
if (mFont.get() == nullptr)
```
WDYT?
