### ISSUE TITLE
OpenDungeons does not compile with gcc 4.7.2

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#483]
As seen on Mageia 3 with gcc 4.7.2, we are now using C++11 features that were not supported yet in gcc 4.7.2:

```
Building CXX object CMakeFiles/opendungeons.dir/source/modes/ConsoleInterface.cpp.o
/home/opendungeons/OpenDungeons/source/modes/ConsoleInterface.cpp: In member function 'bool ConsoleInterface::addCommand(ConsoleInterface::String_t, ConsoleInterface::String_t, ConsoleInterface::CommandFunction_t, std::initializer_list<AbstractModeManager::ModeType>, std::initializer_list<std::basic_string<char> >)':
/home/opendungeons/OpenDungeons/source/modes/ConsoleInterface.cpp:37:17: error: 'using CommandMap_t = class std::map<std::basic_string<char>, std::shared_ptr<Command> >' has no member named 'emplace'
/home/opendungeons/OpenDungeons/source/modes/ConsoleInterface.cpp:40:21: error: 'using CommandMap_t = class std::map<std::basic_string<char>, std::shared_ptr<Command> >' has no member named 'emplace'
```

What should we do about it? Add a mention in the README that gcc >= 4.8.0 is needed?
I guess I'll have to try to package a more recent gcc in my chroot if I want to make development snapshots of the current development branch :)

**Comment by oyvindln** [comment]
Strictly speaking, it's the c++ standard library, not the compiler, but yea, we should add that to the readme.

**Comment by akien-mga** [comment]
Is there a lot to patch to make OD compatible with gcc 4.7.2? I don't mean to go backwards, but maybe we could maintain a patch so that I can still create OD binaries with gcc 4.7.2 (since an "old" glibc is preferable for portable binaries, I don't want to upgrade my chroot to a new release altogether, and building gcc seems a bit hard :-/)

**Comment by oyvindln** [comment]
I don't know, there is a list showing C++11 language support in gcc 4.7, but I can't find a list showing library support, which seems to be the problem here.

**Comment by akien-mga** [comment]
I found this: https://gcc.gnu.org/onlinedocs/gcc-4.7.1/libstdc++/manual/manual/status.html#status.iso.2011

It does have: 23.2.4    - Associative containers -  Partial -   Missing emplace members

**Comment by oyvindln** [comment]
If that is the only issue, changing it wouldn't be a huge problem. Also, from a quick look, it seems it's only debian stable among common distros that doesn't have at least gcc 4.8 in the currently supported versions.

**Comment by Bertram25** [comment]
Is it worth fixing in the code while on the other hand, we just made MSVC 2013 a prerequisite for MS tools liking devs? I would personally fix the doc. WDYT?

**Comment by akien-mga** [comment]
> I would personally fix the doc. WDYT?

I also think that's what we should do in the main tree, there is no need to go backwards IMO.

The main issue for me is that I need to build OD binaries on an _old_ distro (more precisely, against an old enough glibc) to make them portable (because if I build them against glibc 2.21 that I have here, they won't work on most of the distros that are still with glibc <= 2.20). So I chose Mageia 3 since it has glibc 2.17 which is old enough IMO (it's just too new for Debian stable), but then I'm stuck with gcc 4.7.2.

So for the upcoming 0.5.0 portable binaries, I would have two possibilities:
- either patch the code (locally, not in the main repo) to remove the usage of the emplace members; if it's the only change, it seems like a viable solution for the time being;
- or upgrade my chroots to another distro/release. Mageia 4 would have gcc 4.8.2 and glibc 2.18, so maybe that's not too bad either? I'll try to check what the main distros use for glibc versions in their currently supported releases (I know that Ubuntu 14.04 LTS has glibc 2.19 [1], so that would be fine).

[1] http://en.wikipedia.org/wiki/GNU_C_Library#Version_history

**Comment by Bertram25** [comment]
Hmm, Debian 8 is in freeze already, right? May it won't that long.
In any case, if it's about changing two lines of code, yes, we can for it. :)

**Comment by hwoarangmy** [comment]
> either patch the code (locally, not in the main repo) to remove the usage of the emplace members

Whatever the changes are, IMHO, unless there is a huge performance hit, we should use the same sources.
We should just define which systems we want to support and make sure OD sources can be built on them. For windows, it is MinGW 4.8.1 and MSVS2013 express.
For linux, we have to make a choice.

**Comment by Bertram25** [comment]
> For linux, we have to make a choice.

IMO, full standard c++11 support as it is now a reality in most systems, then.
And it's what we agreed about AFAIK.

**Comment by akien-mga** [comment]
> IMO, full standard c++11 support as it is now a reality in most systems, then.
> And it's what we agreed about AFAIK.

Fine by me :-) I'll upgrade my chroots to Mageia 4 then for the portable releases (i.e. glibc 2.18, we should still be okay for most users IMO).

**Comment by hwoarangmy** [comment]
> IMO, full standard c++11 support as it is now a reality in most systems, then.

I had more a glibc/gcc version in mind but I'm not as aware as @akien-mga about distros and most used versions

**Comment by Bertram25** [comment]
Are we got an agreement on this issue, btw?

**Comment by akien-mga** [comment]
I think so: document the minimum GCC version needed in the README (i.e. gcc 4.8.0), and I'll upgrade my chroots to generate the binary releases for 0.5.0 :-)

**Comment by Bertram25** [comment]
Ok, then the readme and faq should be updated. Should the binary builds scripts, too? (I think not but better ask)

**Comment by akien-mga** [comment]
I don't think we need to update the binary build scripts, they are mostly for my own usage for now, and could be a nice resource for one of you or our successors ;) if I were MIA... and when that happens, gcc 4.7.x will be an old memory :-)

**Comment by Bertram25** [comment]
eh eh. Cool to hear. :)
